"""empty message

Revision ID: 7eb9b6cc7810
Revises: None
Create Date: 2016-01-18 13:34:27.857086

"""

# revision identifiers, used by Alembic.
revision = '7eb9b6cc7810'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'posts_pkey')
    )
    ### end Alembic commands ###
